---
image: linuxfoundationit/ansible-openjdk8-maven3.6.1

variables:
  ANSIBLE_STDOUT_CALLBACK: 'unixy'

.docker_template: &docker_definition
  image: docker:stable
  services:
    - docker:dind
  variables:
    DOCKER_HOST: tcp://docker:2375/
    DOCKER_DRIVER: overlay2
    MOUNT_POINT: /builds/project-0/
    IMAGE_TAG: $CI_REGISTRY_IMAGE:$CI_COMMIT_REF_SLUG

docker-verify:
  <<: *docker_definition
  stage: build
  script:
    - docker build .
  only:
    changes:
      - 'Dockerfile'
docker-merge:
  <<: *docker_definition
  stage: deploy
  script:
    - docker login -u $CI_REGISTRY_USER -p $CI_REGISTRY_PASSWORD $CI_REGISTRY
    - docker build -t $IMAGE_TAG .
    - mkdir -p "$MOUNT_POINT"
    - docker run -v "$MOUNT_POINT:/mnt" $IMAGE_TAG -c local "ls /mnt/"
    - docker push $IMAGE_TAG
  only:
    - master
